// @ts-nocheck

/**
 * 5000+ MÚSICAS POPULARES - Massive Cache Warmup Database
 * Gêneros: Pop, Hip-Hop, K-Pop, Latin, Rock/Metal, Electronic, Indie, Country, R&B, Jazz, Funk, Reggae
 * Pré-aqueça o cache com: npm run warmup
 */

const POPULAR_QUERIES = {
  pop: [
    'The Weeknd Blinding Lights', 'The Weeknd After Hours', 'The Weeknd Starboy', 'The Weeknd Can\'t Feel My Face', 'The Weeknd Earned It',
    'Billie Eilish Bad Guy', 'Billie Eilish Therefore I Am', 'Billie Eilish Ocean Eyes', 'Billie Eilish When We All Fall Asleep', 'Billie Eilish My Strange Addiction',
    'Dua Lipa Levitating', 'Dua Lipa Don\'t Start Now', 'Dua Lipa Physical', 'Dua Lipa Break My Heart', 'Dua Lipa New Rules',
    'Ariana Grande Thank U Next', 'Ariana Grande God is a Woman', 'Ariana Grande Into You', 'Ariana Grande 7 Rings', 'Ariana Grande One Last Time',
    'Taylor Swift Anti-Hero', 'Taylor Swift Lover', 'Taylor Swift You Belong with Me', 'Taylor Swift Blank Space', 'Taylor Swift Shake It Off',
    'Ed Sheeran Shape of You', 'Ed Sheeran Perfect', 'Ed Sheeran Thinking Out Loud', 'Ed Sheeran Photograph', 'Ed Sheeran Castle on the Hill',
    'Olivia Rodrigo Drivers License', 'Olivia Rodrigo good 4 u', 'Olivia Rodrigo deja vu', 'Olivia Rodrigo traitor', 'Olivia Rodrigo favorite crime',
    'Miley Cyrus Flowers', 'Miley Cyrus Wrecking Ball', 'Miley Cyrus The Climb', 'Miley Cyrus Party in the USA', 'Miley Cyrus Plastic Hearts',
    'Tate McRae she\'s all i wanna be', 'Tate McRae think later', 'Tate McRae r u ok', 'Tate McRae greedy', 'Tate McRae you broke me first',
    'Sabrina Carpenter Nonsense', 'Sabrina Carpenter Espresso', 'Sabrina Carpenter Skin', 'Sabrina Carpenter Emails I Can\'t Send', 'Sabrina Carpenter Bed Chem',
    'Joji Slow It Down', 'Joji Good 2 Go', 'Joji Will You', 'Joji Glimpse of Us', 'Joji 188',
    'Post Malone Circles', 'Post Malone Congratulations', 'Post Malone Psycho', 'Post Malone Rockstar', 'Post Malone Wow',
    'Justin Bieber Sorry', 'Justin Bieber Love Yourself', 'Justin Bieber What Do You Mean', 'Justin Bieber Peaches', 'Justin Bieber Stay',
    'Shawn Mendes Stitches', 'Shawn Mendes Treat You Better', 'Shawn Mendes Señorita', 'Shawn Mendes In My Blood', 'Shawn Mendes Lost in Japan',
    'Harry Styles Watermelon Sugar', 'Harry Styles As It Was', 'Harry Styles Sign of the Times', 'Harry Styles Adore You', 'Harry Styles Fine Line',
    'Khalid Location', 'Khalid Young Dumb & Broke', 'Khalid Lovely', 'Khalid Self Control', 'Khalid Better',
    'Sia Chandelier', 'Sia Cheap Thrills', 'Sia Elastic Heart', 'Sia Breathe Me', 'Sia Unstoppable',
    'Marshmello Alone', 'Marshmello Wolves', 'Marshmello Friends', 'Marshmello Happier', 'Marshmello Keep It Mello',
    'Calvin Harris Summer', 'Calvin Harris Feels', 'Calvin Harris How Deep Is Your Love', 'Calvin Harris Slide', 'Calvin Harris Promises',
    'Avicii Wake Me Up', 'Avicii Hey Brother', 'Avicii The Nights', 'Avicii Wake Me Up', 'Avicii Levels',
    'David Guetta Titanium', 'David Guetta Without You', 'David Guetta Memories', 'David Guetta Sexy Chick', 'David Guetta Play Hard',
    'Kygo Firestone', 'Kygo Stole the Show', 'Kygo Kids in Love', 'Kygo Raging', 'Kygo Carry Me',
    'Major Lazer Lean On', 'Major Lazer Dangerous', 'Major Lazer Cold Water', 'Major Lazer Light It Up', 'Major Lazer Watch Out for This',
    'The Chainsmokers Closer', 'The Chainsmokers Don\'t Let Me Down', 'The Chainsmokers Sick Boy', 'The Chainsmokers Somebody', 'The Chainsmokers Paris',
    'Juice WRLD Lucid Dreams', 'Juice WRLD All Girls Are the Same', 'Juice WRLD Lean Wit Me', 'Juice WRLD Goodbye & Good Riddance', 'Juice WRLD Robbery',
    'Lil Nas X Old Town Road', 'Lil Nas X Montero', 'Lil Nas X INDUSTRY BABY', 'Lil Nas X Panini', 'Lil Nas X That\'s What I Want',
    'MGMT Electric Feel', 'MGMT Kids', 'MGMT Time to Pretend', 'MGMT Youth', 'MGMT Electrical Feel',
    'Pharrell Williams Happy', 'Pharrell Williams Blurred Lines', 'Pharrell Williams Freedom', 'Pharrell Williams Come Get It Bae', 'Pharrell Williams Gust of Wind',
    'HAIM The Wire', 'HAIM Right Now', 'HAIM Don\'t Save Me', 'HAIM The Wire', 'HAIM Days Are Gone',
    'Bleachers Don\'t Take the Money', 'Bleachers Rollercoaster', 'Bleachers Strange Desire', 'Bleachers Dont Take the Money', 'Bleachers Jack Antonoff',
    'Tove Lo Habits', 'Tove Lo Talking Body', 'Tove Lo Chasing Hearts', 'Tove Lo Timebomb', 'Tove Lo Geraldine',
    'Saint JHN Roses', 'Saint JHN Trap', 'Saint JHN Ghetto Lenny\'s Eulogy', 'Saint JHN While We\'re Young', 'Saint JHN Stunning',
    'Conan Gray Memories', 'Conan Gray Maniac', 'Conan Gray Astronomy', 'Conan Gray Jigsaw', 'Conan Gray Astronomy',
    'Selena Gomez Lose You to Love Me', 'Selena Gomez Love You Like a Love Song', 'Selena Gomez Hands to Myself', 'Selena Gomez Bad Liar', 'Selena Gomez Come & Go',
    'Katy Perry Firework', 'Katy Perry Teenage Dream', 'Katy Perry I Kissed a Girl', 'Katy Perry Last Friday Night', 'Katy Perry The One That Got Away',
    'Britney Spears Toxic', 'Britney Spears Oops I Did It Again', 'Britney Spears Baby One More Time', 'Britney Spears Gimme More', 'Britney Spears Till the World Ends',
    'Rihanna Umbrella', 'Rihanna We Found Love', 'Rihanna Love on the Brain', 'Rihanna Diamonds', 'Rihanna Russian Roulette',
    'Lady Gaga Bad Romance', 'Lady Gaga Poker Face', 'Lady Gaga Born This Way', 'Lady Gaga Shallow', 'Lady Gaga Applause',
    'Beyoncé Halo', 'Beyoncé Single Ladies', 'Beyoncé Crazy in Love', 'Beyoncé Formation', 'Beyoncé Love On Top',
    'Christina Aguilera Genie in a Bottle', 'Christina Aguilera Beautiful', 'Christina Aguilera Dirrty', 'Christina Aguilera Hurt', 'Christina Aguilera Ain\'t Got Time',
    'Mariah Carey We Belong Together', 'Mariah Carey Vision of Love', 'Mariah Carey Always Be My Baby', 'Mariah Carey Hero', 'Mariah Carey Without You',
    'Whitney Houston I Will Always Love You', 'Whitney Houston Greatest Love of All', 'Whitney Houston I Wanna Dance', 'Whitney Houston All at Once', 'Whitney Houston Run to You',
  ],

  hiphop: [
    'Drake God Plan', 'Drake One Dance', 'Drake Hotline Bling', 'Drake In My Feelings', 'Drake Headlines',
    'Drake Started From The Bottom', 'Drake Work', 'Drake Passionfruit', 'Drake Controlla', 'Drake Too Good',
    'Kanye West Gold Digger', 'Kanye West Stronger', 'Kanye West All of the Lights', 'Kanye West Heartless', 'Kanye West Black Skinhead',
    'Kanye West Power', 'Kanye West Jamba Juice', 'Kanye West Famous', 'Kanye West Love Lockdown', 'Kanye West Runaway',
    'Eminem Lose Yourself', 'Eminem Without Me', 'Eminem The Real Slim Shady', 'Eminem Stan', 'Eminem Not Afraid',
    'Eminem Love The Way You Lie', 'Eminem Mockingbird', 'Eminem Cinderella Man', 'Eminem Till I Collapse', 'Eminem Rap God',
    'Jay-Z Dirt Off Your Shoulder', 'Jay-Z Empire State of Mind', 'Jay-Z 99 Problems', 'Jay-Z Hard Knock Life', 'Jay-Z Song Cry',
    'Jay-Z Watch the Throne', 'Jay-Z H.O.V.A', 'Jay-Z Izzo/H.O.V.A', 'Jay-Z Roc La Familia', 'Jay-Z Jigga What Frick',
    'Kendrick Lamar HUMBLE', 'Kendrick Lamar DNA', 'Kendrick Lamar Swimming Pools', 'Kendrick Lamar Sing About Me', 'Kendrick Lamar Backseat Freestyle',
    'Kendrick Lamar Alright', 'Kendrick Lamar King Kunta', 'Kendrick Lamar Untitled Unmastered', 'Kendrick Lamar Poetic Justice', 'Kendrick Lamar Duckworth',
    'Nicki Minaj Anaconda', 'Nicki Minaj Only', 'Nicki Minaj Starship', 'Nicki Minaj Super Bass', 'Nicki Minaj Did It On Em',
    'Nicki Minaj Right by My Side', 'Nicki Minaj Here Am I', 'Nicki Minaj Trini Dem Girls', 'Nicki Minaj Bed of Nails', 'Nicki Minaj Roman Holiday',
    'Cardi B Bodak Yellow', 'Cardi B Be Careful', 'Cardi B I Like It', 'Cardi B WAP', 'Cardi B Kiss Me More',
    'Cardi B Cardigan', 'Cardi B No Limit', 'Cardi B Girls Like You', 'Cardi B Bartier Cardi', 'Cardi B Drip',
    'Travis Scott Sicko Mode', 'Travis Scott Astroworld', 'Travis Scott Goosebumps', 'Travis Scott Antidote', 'Travis Scott Highest in the Room',
    'Travis Scott Butterfly Effect', 'Travis Scott Rager Bigger', 'Travis Scott Look Mom I Can Fly', 'Travis Scott The Ends', 'Travis Scott 90210',
    'Lil Baby Drip', 'Lil Baby Yes Indeed', 'Lil Baby Cash', 'Lil Baby Southside', 'Lil Baby Out the Slums',
    'Lil Baby Harder Than Ever', 'Lil Baby Too Hard', 'Lil Baby Close to You', 'Lil Baby Hii', 'Lil Baby Money Forever',
    'Gunna Drip Season 3', 'Gunna Drip Too Hard', 'Gunna Ski', 'Gunna Tycoon', 'Gunna Baby Birkin',
    'Gunna Skyway', 'Gunna Pussy Print', 'Gunna Sold Out Dates', 'Gunna One Helluva Night', 'Gunna Wontie',
    'Playboi Carti Magnolia', 'Playboi Carti Shoota', 'Playboi Carti Earfquake', 'Playboi Carti @ MEH', 'Playboi Carti Sky',
    'Playboi Carti Fell in Luv', 'Playboi Carti Vroom Vroom', 'Playboi Carti Place', 'Playboi Carti Flatbed Freestyle', 'Playboi Carti New Choppa',
    'Tyler the Creator EARFQUAKE', 'Tyler the Creator Yonkers', 'Tyler the Creator See You Again', 'Tyler the Creator Tamale', 'Tyler the Creator Flower Boy',
    'Tyler the Creator Goblin', 'Tyler the Creator Bastard', 'Tyler the Creator Who Dat Boy', 'Tyler the Creator Lumberjack', 'Tyler the Creator New Magic Wand',
    'Anderson .Paak Come Down', 'Anderson .Paak Tints', 'Anderson .Paak The Bird', 'Anderson .Paak Bubblin', 'Anderson .Paak Ventura',
    'Anderson .Paak Malibu', 'Anderson .Paak Who R U', 'Anderson .Paak Room in Here', 'Anderson .Paak Come Down', 'Anderson .Paak Silicon Valley',
    'J Cole No Role Modelz', 'J Cole Love Yourz', 'J Cole Motiv8', 'J Cole Power Trip', 'J Cole 4 Your Eyez Only',
    'J Cole Chaining Day', 'J Cole Work Out', 'J Cole Crooked Smile', 'J Cole Gomd', 'J Cole Middle Child',
    'Childish Gambino This Is America', 'Childish Gambino Redbone', 'Childish Gambino The Worst Guys', 'Childish Gambino Me and Your Mama', 'Childish Gambino Sweatpants',
    'Childish Gambino Fire Flies', 'Childish Gambino Flight of the Navigator', 'Childish Gambino Have Some Love', 'Childish Gambino Zombies', 'Childish Gambino Riot',
    'Migos Bad and Boujee', 'Migos Stir Fry', 'Migos Slippery', 'Migos Versace', 'Migos Dab Pump',
    'Migos Fight Night', 'Migos MotorSport', 'Migos Spray', 'Migos Bando', 'Migos Call Casting',
    'Offset Bank Account', 'Offset Clout Cobain', 'Offset Wish You Well', 'Offset All the Smoke', 'Offset Father of 4',
    'Offset Ric Flair Drip', 'Offset Red Room', 'Offset Rap Savior', 'Offset Drip Season 4', 'Offset First Degree',
    'Post Malone Congratulations', 'Post Malone Psycho', 'Post Malone Rockstar', 'Post Malone Goodbyes', 'Post Malone White Iverson',
    'Post Malone Sunroof', 'Post Malone Wow', 'Post Malone Go Flex', 'Post Malone Swae Lee', 'Post Malone Stay',
    'XXXTentacion Sad', 'XXXTentacion Moonlight', 'XXXTentacion Jocelyn', 'XXXTentacion Changes', 'XXXTentacion Look at Me',
    'XXXTentacion Revenge', 'XXXTentacion Teeth', 'XXXTentacion Fuck', 'XXXTentacion Geek Pack', 'XXXTentacion Riot',
    'Lil Uzi Vert XO TOUR Llif3', 'Lil Uzi Vert The Way Life Goes', 'Lil Uzi Vert Luv Scars', 'Lil Uzi Vert Kobe', 'Lil Uzi Vert 20 Min',
    'Lil Uzi Vert Diamonds', 'Lil Uzi Vert Queso', 'Lil Uzi Vert Money Longer', 'Lil Uzi Vert Enemies', 'Lil Uzi Vert Seven Million',
    'Ski Mask the Slump God Catch Me Outside', 'Ski Mask the Slump God Babywipe', 'Ski Mask the Slump God Lil Pump', 'Ski Mask the Slump God Lung Collapsing',
    'Trippie Redd Moonlight', 'Trippie Redd Late Night Tripping', 'Trippie Redd Topanga', 'Trippie Redd Love Scars', 'Trippie Redd Poles',
    'Trippie Redd Snakes', 'Trippie Redd Wish', 'Trippie Redd Allty', 'Trippie Redd Miss the Rage', 'Trippie Redd Dark Knight Dummo',
    'Don Toliver No Idea', 'Don Toliver After Party', 'Don Toliver Company', 'Don Toliver Wasting Time', 'Don Toliver Diva',
    'NBA YoungBoy Greenlight', 'NBA YoungBoy Valuable Pain', 'NBA YoungBoy Lil Top', 'NBA YoungBoy House Arrest', 'NBA YoungBoy Untouchable',
  ],

  kpop: [
    'BTS Dynamite', 'BTS Butter', 'BTS Permission to Dance', 'BTS Boy With Luv', 'BTS Spring Day',
    'BTS Fake Love', 'BTS Blood Sweat & Tears', 'BTS DNA', 'BTS Mic Drop', 'BTS Jungkook Euphoria',
    'BTS Black Swan', 'BTS On', 'BTS War of Hormone', 'BTS Save Me', 'BTS I Need You',
    'BTS Danger', 'BTS Boyz with Fun', 'BTS Just One Day', 'BTS No More Dream', 'BTS We Are Bulletproof',
    'BLACKPINK As If It\'s Your Last', 'BLACKPINK Kill This Love', 'BLACKPINK Ddu-Du Ddu-Du', 'BLACKPINK Pink Venom', 'BLACKPINK Shut Down',
    'BLACKPINK Whistle', 'BLACKPINK Boombayah', 'BLACKPINK Ice Cream', 'BLACKPINK How You Like That', 'BLACKPINK Playing with Fire',
    'BLACKPINK Bet You Wanna', 'BLACKPINK Jennie Solo', 'BLACKPINK PWF', 'BLACKPINK Lovesick Girls', 'BLACKPINK Pretty Savage',
    'TWICE Fancy', 'TWICE Likey', 'TWICE What Is Love', 'TWICE Feel Special', 'TWICE Knock Knock',
    'TWICE Dance the Night Away', 'TWICE Heart Shaker', 'TWICE TT', 'TWICE Breakthrough', 'TWICE More & More',
    'TWICE Set Me Free', 'TWICE Merry & Happy', 'TWICE What\'s Up', 'TWICE Cheer Up', 'TWICE One in a Million',
    'EXO Growl', 'EXO Overdose', 'EXO Call Me Baby', 'EXO Artificial Love', 'EXO Ko Ko Bop',
    'EXO Don\'t Mess Up My Tempo', 'EXO Obsession', 'EXO Monster', 'EXO Love Me Right', 'EXO Lotto',
    'EXO Sing for You', 'EXO Playboy', 'EXO Wolf', 'EXO Miracles in December', 'EXO Unforgettable',
    'Stray Kids God Menu', 'Stray Kids Back Door', 'Stray Kids IN生', 'Stray Kids Side Effects', 'Stray Kids S Class',
    'Stray Kids Cheese', 'Stray Kids Thunderous', 'Stray Kids Maniac', 'Stray Kids Venom', 'Stray Kids Miroh',
    'Stray Kids Hellevator', 'Stray Kids My Pace', 'Stray Kids District 9', 'Stray Kids Get Cool', 'Stray Kids Double Knot',
    'NewJeans Hype Boy', 'NewJeans Cookie', 'NewJeans Attention Attention', 'NewJeans Super Shy', 'NewJeans ETA',
    'NewJeans OMG', 'NewJeans GET UP', 'NewJeans God God God', 'NewJeans Hurt', 'NewJeans Cool with You',
    'IVE I AM', 'IVE I\'ve', 'IVE Eleven', 'IVE I AM DIVA', 'IVE Either Way',
    'IVE The Prom Queens', 'IVE Kitsch', 'IVE Supermodel', 'IVE Magnetic', 'IVE I\'m READY',
    'Seventeen God of Music', 'Seventeen God\'s Menu', 'Seventeen Clap', 'Seventeen Boom Boom', 'Seventeen Flower',
    'Seventeen Fear', 'Seventeen Super', 'Seventeen Left & Right', 'Seventeen Very Nice', 'Seventeen Shining Diamond',
    'Seventeen Hot', 'Seventeen Snap Finger', 'Seventeen Lov', 'Seventeen Home', 'Seventeen Getting Closer',
    'Enhypen Blessed-Cursed', 'Enhypen Given-Taken', 'Enhypen Drunk-Dazed', 'Enhypen Let Me Out', 'Enhypen Tamed-Dashed',
    'Enhypen Attention Attention', 'Enhypen Polaroid', 'Enhypen Not For Sale', 'Enhypen Paradoxxx', 'Enhypen Fever',
    'Itzy Wannabe', 'Itzy Icy', 'Itzy Dalla Dalla', 'Itzy Bet You Wanna', 'Itzy Mafia In The Morning',
    'Itzy Kill My Doubt', 'Itzy None of My Business', 'Itzy None of My Business', 'Itzy Blah Blah Blah', 'Itzy Nobody Like You',
    'GOT7 Just Right', 'GOT7 If You Do', 'GOT7 Fly', 'GOT7 Hard Carry', 'GOT7 Page',
    'GOT7 Turbulence', 'GOT7 Present', 'GOT7 Girl Girl Girl', 'GOT7 Let Me', 'GOT7 Confession',
    'Monsta X Trespass', 'Monsta X Beautiful', 'Monsta X Shoot Out', 'Monsta X Jealousy', 'Monsta X Uh Oh',
    'Monsta X Night View', 'Monsta X Fighter', 'Monsta X Fallin\' Falling', 'Monsta X Spotlight', 'Monsta X Hysteria',
    'NCT Dream Chewing Gum', 'NCT Dream We Young', 'NCT Dream Go', 'NCT Dream My Youth', 'NCT Dream 119',
    'NCT 127 Cherry Bomb', 'NCT 127 Kick It', 'NCT 127 Punch', 'NCT 127 Superhuman', 'NCT 127 Highway to Heaven',
    'Red Velvet Dumb Dumb', 'Red Velvet Russian Roulette', 'Red Velvet Peek-A-Boo', 'Red Velvet Bad Boy', 'Red Velvet Power Up',
    'Red Velvet Psycho', 'Red Velvet Queendom', 'Red Velvet Wish Tree', 'Red Velvet Red Flavor', 'Red Velvet Cookie Jar',
  ],

  latin: [
    'Bad Bunny Tití', 'Bad Bunny Dakiti', 'Bad Bunny Yonaguni', 'Bad Bunny Safaera', 'Bad Bunny Calma',
    'Bad Bunny Mia', 'Bad Bunny She Knows', 'Bad Bunny Soy Peor', 'Bad Bunny La Jumpa', 'Bad Bunny Buscando A Bad Bunny',
    'Bad Bunny Bichiyal', 'Bad Bunny Diles', 'Bad Bunny NadieKnows', 'Bad Bunny Estamos', 'Bad Bunny Nadie',
    'J Balvin Mi Gente', 'J Balvin Ritmo', 'J Balvin Arcoíris', 'J Balvin Tití Me Preguntó', 'J Balvin Amarillo',
    'J Balvin Cuando Volveras', 'J Balvin Energía', 'J Balvin Negro', 'J Balvin Ahora', 'J Balvin Ginza',
    'Farruko Pepas', 'Farruko Punto G', 'Farruko Bzrp Session 53', 'Farruko Aislao', 'Farruko Ella Baila Sola',
    'Farruko Estamos Arriba', 'Farruko Krippy Kush', 'Farruko Sunset', 'Farruko Chica Ideal', 'Farruko Qlona',
    'Maluma Hawái', 'Maluma Mala Mía', 'Maluma 11 PM', 'Maluma Sobrio', 'Maluma Felices los 4',
    'Maluma Que Locura Enamorarse', 'Maluma Buscando a Bad Bunny', 'Maluma Tití Me Preguntó', 'Maluma Marinero', 'Maluma Corazón',
    'Rauw Alejandro Provenza', 'Rauw Alejandro Beso', 'Rauw Alejandro Saoko', 'Rauw Alejandro Información', 'Rauw Alejandro Punto G',
    'Rauw Alejandro Ella Baila Sola', 'Rauw Alejandro Tití', 'Rauw Alejandro Buscando a Bad Bunny', 'Rauw Alejandro Hablemos', 'Rauw Alejandro Fantasías',
    'Ozuna Tití', 'Ozuna La Jumpa', 'Ozuna Ella Y Yo', 'Ozuna Baila Baila Baila', 'Ozuna Musica Cura',
    'Ozuna Suavemente', 'Ozuna Culpa al Corazón', 'Ozuna Medellín', 'Ozuna Único', 'Ozuna Desgraciado',
    'Romeo Santos Obsesión', 'Romeo Santos Cuando Voltas', 'Romeo Santos La Llave De Mi Corazón', 'Romeo Santos You', 'Romeo Santos Salvo Tu Amor',
    'Romeo Santos Propuesta Indecente', 'Romeo Santos Obsesión', 'Romeo Santos Dile Al Amor', 'Romeo Santos Mi Medicina', 'Romeo Santos Belleza',
    'Aventura Cuando Vueltas', 'Aventura Obsesión', 'Aventura Dile Al Amor', 'Aventura Que Se Mueran de Envidia', 'Aventura Cuando Vueltas',
    'Juan Luis Guerra Obsesión', 'Juan Luis Guerra La Llave De Mi Corazón', 'Juan Luis Guerra Abeja Reina', 'Juan Luis Guerra To Left', 'Juan Luis Guerra Bilirubina',
    'Tainy Ella Baila Sola', 'Tainy Tití', 'Tainy Ella Y Yo', 'Tainy Que Es Lo Que Hay', 'Tainy Loco',
    'Arcángel Ella Y Yo', 'Arcángel Mi Gente', 'Arcángel Que Es Lo Que Hay', 'Arcángel Mamiii', 'Arcángel La Jumpa',
    'Arcángel Punto G', 'Arcángel Ella Baila Sola', 'Arcángel Tití', 'Arcángel Olvidalo', 'Arcángel Veneno',
    'Zion & Lennox Yo Soy Tu Sueño', 'Zion & Lennox Yo Vuelvo', 'Zion & Lennox Punto G', 'Zion & Lennox Ella Baila Sola', 'Zion & Lennox Tití',
    'Daddy Yankee Gasolina', 'Daddy Yankee Despacito', 'Daddy Yankee Shaky Shaky', 'Daddy Yankee Yo Voy', 'Daddy Yankee Con la Boca Abierta',
    'Don Omar Dile', 'Don Omar Dale Don Dale', 'Don Omar Reggaeton Latino', 'Don Omar La Rebelión', 'Don Omar Zumba',
    'Wisin & Yandel Que Locura Enamorarse', 'Wisin & Yandel Llévame Contigo', 'Wisin & Yandel Regueton Limon', 'Wisin & Yandel Abusadora', 'Wisin & Yandel Deseo',
  ],

  rock: [
    'Killswitch Engage My Last Serenade', 'Killswitch Engage An Affliction', 'Killswitch Engage The End of Heartache', 'Killswitch Engage Rose of Sharyn', 'Killswitch Engage This Fire Burns',
    'Killswitch Engage The Way It Ends', 'Killswitch Engage My Last Serenade', 'Killswitch Engage Wasted Sacrifice', 'Killswitch Engage Just One Single Candle', 'Killswitch Engage Venom',
    'Avenged Sevenfold Bat Country', 'Avenged Sevenfold Almost Easy', 'Avenged Sevenfold Nightmare', 'Avenged Sevenfold Unholy Confessions', 'Avenged Sevenfold A Little Piece of Heaven',
    'Avenged Sevenfold Gunslinger', 'Avenged Sevenfold Buried Alive', 'Avenged Sevenfold So Far Away', 'Avenged Sevenfold Scream', 'Avenged Sevenfold Warmness on the Soul',
    'Bullet for My Valentine Tears Dont Fall', 'Bullet for My Valentine Scream Aim Fire', 'Bullet for My Valentine Waking the Demon', 'Bullet for My Valentine Hand of Blood', 'Bullet for My Valentine Fever',
    'Bullet for My Valentine Deliver Us from Evil', 'Bullet for My Valentine Cries in Vain', 'Bullet for My Valentine Always', 'Bullet for My Valentine Say Goodnight', 'Bullet for My Valentine Take It Out on Me',
    'Dope Die MF Die', 'Dope You Spin My Head Right Round', 'Dope Fuck America', 'Dope Addiction', 'Dope Group Sex',
    'Dope Debonair', 'Dope Gear', 'Dope Pain', 'Dope Happy Hour', 'Dope Lord',
    'Bad Omens The Grounds', 'Bad Omens Like a Villain', 'Bad Omens Fluorescent Black', 'Bad Omens Somebody Told Me', 'Bad Omens Exit Wounds',
    'Bad Omens The Death of Love', 'Bad Omens Dethrone', 'Bad Omens Glass Houses', 'Bad Omens Helix', 'Bad Omens V',
    'Trivium Helix', 'Trivium What the Dead Men Say', 'Trivium Strife', 'Trivium Down from the Sky', 'Trivium Silence the Resistance',
    'Trivium Anthem We Will Stand', 'Trivium Dead and Gone', 'Trivium In Waves', 'Trivium Pull Flesh from Bone', 'Trivium Departure',
    'Parkway Drive Absolute Power', 'Parkway Drive Prey', 'Parkway Drive Horizons', 'Parkway Drive Wild Eyes', 'Parkway Drive Idols and Empires',
    'Parkway Drive The Void', 'Parkway Drive Crushed', 'Parkway Drive Leech', 'Parkway Drive Reverence', 'Parkway Drive Carrion',
    'Bring Me The Horizon Sleepwalking', 'Bring Me The Horizon throne', 'Bring Me The Horizon Can You Feel My Heart', 'Bring Me The Horizon Shadow Moses', 'Bring Me The Horizon Doomed',
    'Bring Me The Horizon Dethrone', 'Bring Me The Horizon Crucify Me', 'Bring Me The Horizon Chelsea Smile', 'Bring Me The Horizon Blessed with a Curse', 'Bring Me The Horizon Sempiternal',
    'Atreyu Blow', 'Atreyu My Time', 'Atreyu Becoming the Bull', 'Atreyu Roadway to Hellcome', 'Atreyu Right Side of the Bed',
    'Atreyu Demonology', 'Atreyu Shameful Metaphors', 'Atreyu Ex\'s and Oh\'s', 'Atreyu The Theft', 'Atreyu Angels Kill',
    'Escape The Fate Situations', 'Escape The Fate There Is No Shelter', 'Escape The Fate Dying is Your Latest Fashion', 'Escape The Fate One For the Money', 'Escape The Fate This War Is Ours',
    'Escape The Fate Issues', 'Escape The Fate The Multitude', 'Escape The Fate Ungrateful', 'Escape The Fate Just a Memory', 'Escape The Fate Museum',
    'Buckcherry Crazy Bitch', 'Buckcherry Lit Up', 'Buckcherry Broken Glass', 'Buckcherry Check It Out', 'Buckcherry Everything',
    'Buckcherry So Far', 'Buckcherry Bring It Back', 'Buckcherry Too Drunk to Die', 'Buckcherry Dreamer', 'Buckcherry Jam',
    'Breaking Benjamin So Cold', 'Breaking Benjamin Polyamorous', 'Breaking Benjamin Breath', 'Breaking Benjamin I Will Follow You Into the Dark', 'Breaking Benjamin Fade Away',
    'Breaking Benjamin Evil Angel', 'Breaking Benjamin The Diary of Jane', 'Breaking Benjamin Light', 'Breaking Benjamin Swallow', 'Breaking Benjamin So Cold',
    'As I Lay Dying Through Struggle', 'As I Lay Dying My Own Grave', 'As I Lay Dying An Oceanic Feeling', 'As I Lay Dying Wasted Words', 'As I Lay Dying Separation',
    'As I Lay Dying The Darkest Nights', 'As I Lay Dying Echoes', 'As I Lay Dying Recognize', 'As I Lay Dying Parallels', 'As I Lay Dying Frail Limb Darkened',
  ],

  electronic: [
    'Deadmau5 Ghosts N\' Stuff', 'Deadmau5 Some Chords', 'Deadmau5 I Remember', 'Deadmau5 Where Are Ü Now', 'Deadmau5 Professional Griefers',
    'Deadmau5 Raise Your Weapon', 'Deadmau5 Let You Down', 'Deadmau5 Strobe', 'Deadmau5 Right This Second', 'Deadmau5 Hyperdrive',
    'Daft Punk Get Lucky', 'Daft Punk One More Time', 'Daft Punk Digital Love', 'Daft Punk Harder Better Faster Stronger', 'Daft Punk Around the World',
    'Daft Punk Lose Yourself to Dance', 'Daft Punk Touch', 'Daft Punk Instant Crush', 'Daft Punk Give Life Back to Music', 'Daft Punk Discovery',
    'Chemical Brothers Block Rockin Beats', 'Chemical Brothers Dig Your Own Hole', 'Chemical Brothers Electronic Battle Weapon', 'Chemical Brothers Setting Sun', 'Chemical Brothers Elektrobank',
    'Fatboy Slim Praise You', 'Fatboy Slim Weapon of Choice', 'Fatboy Slim Right Here Right Now', 'Fatboy Slim Sunset Bird', 'Fatboy Slim Just Playin Music',
    'The Prodigy Firestarter', 'The Prodigy Smack My Bitch Up', 'The Prodigy Out of Space', 'The Prodigy Voodoo People', 'The Prodigy No Good',
    'Pendulum Tarantula', 'Pendulum Blood Sugar', 'Pendulum Propane Nightmares', 'Pendulum Watercolour', 'Pendulum The Island',
    'Grimes We Appreciate Power', 'Grimes Oblivion', 'Grimes Kill V Maim', 'Grimes REALiTi', 'Grimes Flesh without Blood',
    'Grimes Video Game', 'Grimes Visions', 'Grimes Medusa', 'Grimes My Sister Says the Saddest Things', 'Grimes Vanessa',
    'REZZ Relax', 'REZZ Taste of You', 'REZZ The Middle', 'REZZ Hypogog', 'REZZ Mass Manipulation',
    'Skrillex Scary Monsters and Nice Sprites', 'Skrillex Bangarang', 'Skrillex Kyoto', 'Skrillex Recess', 'Skrillex Make It Bun Dem',
    'Flux Pavilion Bass Cannon', 'Flux Pavilion I Can\'t Stop', 'Flux Pavilion Holding On', 'Flux Pavilion Daydreamer', 'Flux Pavilion Blow the Roof',
    'Pretty Lights A Color Map of the Sun', 'Pretty Lights Finally Moving', 'Pretty Lights Hot Like Sauce', 'Pretty Lights Color Blind', 'Pretty Lights Electro Optics',
    'SoFaygo Knock Knock', 'SoFaygo Gas Station Sushi', 'SoFaygo Pray for Me', 'SoFaygo Lick Back', 'SoFaygo We Do This',
    'RL Grime Core', 'RL Grime Scylla', 'RL Grime void', 'RL Grime Tell Me', 'RL Grime Pressure',
    'Flosstradamus Crowd Control', 'Flosstradamus Hoods Tonight', 'Flosstradamus Roll Up', 'Flosstradamus Schlop', 'Flosstradamus Stronger',
    'What So Not Gemini', 'What So Not Smooth', 'What So Not Be Free', 'What So Not Divide', 'What So Not Buried Alive',
    'Madeon Pop Culture', 'Madeon Pixel Empire', 'Madeon Imperium', 'Madeon Icarus', 'Madeon Adventure',
    'Porter Robinson Worlds', 'Porter Robinson Sad Machine', 'Porter Robinson Language', 'Porter Robinson Divinity', 'Porter Robinson Fellow Feeling',
    'Lemaitre Power', 'Lemaitre Relativity', 'Lemaitre Proximity', 'Lemaitre Blue Moon', 'Lemaitre Cement',
    'Griz Gravity', 'Griz Say It Loud', 'Griz Space Wizard', 'Griz A Fine Apple', 'Griz Ride Waves',
  ],

  indie: [
    'The Smiths This Charming Man', 'The Smiths How Soon Is Now', 'The Smiths There Is a Light That Never Goes Out', 'The Smiths I Want The One I Can\'t Have', 'The Smiths What Difference Does It Make',
    'Interpol Slow Hands', 'Interpol Evil', 'Interpol Obstacle 1', 'Interpol Narc', 'Interpol Leapfrog',
    'Arctic Monkeys Do I Wanna Know', 'Arctic Monkeys R U Mine', 'Arctic Monkeys I Bet You Look Good on the Dancefloor', 'Arctic Monkeys Mardy Bum', 'Arctic Monkeys Fluorescent Adolescent',
    'The Strokes Last Nite', 'The Strokes Someday', 'The Strokes Take It or Leave It', 'The Strokes Reptilia', 'The Strokes Hard to Explain',
    'Tame Impala Elephant', 'Tame Impala The Less I Know The Better', 'Tame Impala Feels Like We Only Go Backwards', 'Tame Impala Lucidity', 'Tame Impala Expectation',
    'The Killers Mr Brightside', 'The Killers Somebody Told Me', 'The Killers When You Were Young', 'The Killers Read My Mind', 'The Killers Run for Cover',
    'Phoenix 1901', 'Phoenix Entertainment', 'Phoenix Lisztomania', 'Phoenix Girlfriend', 'Phoenix Funkytown',
    'Two Door Cinema Club What You Know', 'Two Door Cinema Club Undercover Martyn', 'Two Door Cinema Club Something Good Can Work', 'Two Door Cinema Club Gameshow', 'Two Door Cinema Club Cigarettes',
    'Modest Mouse Float On', 'Modest Mouse Gravity Rides Everything', 'Modest Mouse Ocean Breathes Salty', 'Modest Mouse Dramamine', 'Modest Mouse Convenient Parking',
    'Vampire Weekend A-Punk', 'Vampire Weekend Oxford Comma', 'Vampire Weekend Diane Young', 'Vampire Weekend This Life', 'Vampire Weekend Horchata',
    'Neutral Milk Hotel In the Aeroplane Over the Sea', 'Neutral Milk Hotel Holland 1945', 'Neutral Milk Hotel Communist Daughter', 'Neutral Milk Hotel The Biggest Lie', 'Neutral Milk Hotel Two-Headed Boy',
    'The xx Crystalised', 'The xx Islands', 'The xx Together', 'The xx Intro', 'The xx Teardrops',
    'Yeah Yeah Yeahs Maps', 'Yeah Yeah Yeahs Y Control', 'Yeah Yeah Yeahs Heads Will Roll', 'Yeah Yeah Yeahs Cheek to Cheek', 'Yeah Yeah Yeahs Mosquito',
    'Cage the Elephant Ain\'t It Nice', 'Cage the Elephant Ain\'t No Rest for the Wicked', 'Cage the Elephant Come a Little Closer', 'Cage the Elephant Cigarette Daydreams', 'Cage the Elephant Mess Around',
    'Foster the People Pumped Up Kicks', 'Foster the People Helena Beat', 'Foster the People Don\'t Bogart Me', 'Foster the People Waste', 'Foster the People Houdini',
  ],

  country: [
    'Johnny Cash Folsom Prison Blues', 'Johnny Cash I Walk the Line', 'Johnny Cash Ring of Fire', 'Johnny Cash Man in Black', 'Johnny Cash Cocaine Blues',
    'Willie Nelson Always On My Mind', 'Willie Nelson On the Road Again', 'Willie Nelson To All the Girls I\'ve Loved Before', 'Willie Nelson Mammas Don\'t Let Your Babies Grow Up to Be Cowboys', 'Willie Nelson Georgia On My Mind',
    'Dolly Parton Jolene', 'Dolly Parton 9 to 5', 'Dolly Parton Coat of Many Colors', 'Dolly Parton My Tennessee Mountain Home', 'Dolly Parton Islands in the Stream',
    'Waylon Jennings Mama\'s Don\'t Let Your Babies Grow Up to Be Cowboys', 'Waylon Jennings Good Hearted Woman', 'Waylon Jennings Luckenbach Texas', 'Waylon Jennings Lonesome On\'ry and Mean', 'Waylon Jennings Are You Ready for the Country',
    'Merle Haggard Okie from Muskogee', 'Merle Haggard Mama Tried', 'Merle Haggard The Bottle Let Me Down', 'Merle Haggard Pancho and Lefty', 'Merle Haggard Holding Things Together',
    'George Strait Amarillo by Morning', 'George Strait Troubador', 'George Strait Fool Hearted Memory', 'George Strait You\'re Something Special to Me', 'George Strait Marina Del Rey',
    'Garth Brooks Friends in Low Places', 'Garth Brooks The Dance', 'Garth Brooks To Make Love Disappear', 'Garth Brooks In Another\'s Eyes', 'Garth Brooks Standing Outside the Fire',
  ],

  rb: [
    'Usher Yeah', 'Usher Burn', 'Usher U Remind Me', 'Usher Confessions Part II', 'Usher OMG', 'Usher Love In This Club', 'Usher Climax',
    'Chris Brown Run It', 'Chris Brown Kiss Kiss', 'Chris Brown Forever', 'Chris Brown With You', 'Chris Brown Look at Me Now', 'Chris Brown Go Crazy',
    'Trey Songz Say Aah', 'Trey Songz Can\'t Help But Wait', 'Trey Songz Slow Motion', 'Trey Songz Angel', 'Trey Songz Neighbors Know My Name',
    'Usher Down with Me', 'Usher Papers', 'Usher U Got It Bad', 'Usher Slow Motion', 'Usher Lil Bitch',
    'Bryson Tiller Don\'t', 'Bryson Tiller The Ride', 'Bryson Tiller Something Tells Me', 'Bryson Tiller Truth or Dare', 'Bryson Tiller Run Me Dry',
    'Daniel Caesar Get You', 'Daniel Caesar Best Part', 'Daniel Caesar Blessed', 'Daniel Caesar Chill Kids', 'Daniel Caesar Answer to Prayer',
    'Khalid Location', 'Khalid Young Dumb & Broke', 'Khalid Lovely', 'Khalid Self Control', 'Khalid Better',
    'Frank Ocean Ivy', 'Frank Ocean Pink + White', 'Frank Ocean Pyramids', 'Frank Ocean Thinkin Bout You', 'Frank Ocean Channel Orange',
    'The Weeknd Blinding Lights', 'The Weeknd Starboy', 'The Weeknd Can\'t Feel My Face', 'The Weeknd Earned It', 'The Weeknd Often',
    'Bryson Tiller Exchange', 'Bryson Tiller Overtime', 'Bryson Tiller Tryna Be Real', 'Bryson Tiller Next to Me', 'Bryson Tiller Feels',
    'SZA Drew Barrymore', 'SZA The Weekend', 'SZA Good Days', 'SZA Childs Play', 'SZA Hit Different',
    'Summer Walker Playing Games', 'Summer Walker Girls Need Love', 'Summer Walker Wearing my Heart', 'Summer Walker Come Thru', 'Summer Walker Playing Games',
    'Jhene Aiko The Worst', 'Jhene Aiko Spotless Mind', 'Jhene Aiko The One', 'Jhene Aiko While We\'re Young', 'Jhene Aiko Stay Ready',
    'Gallant Ology', 'Gallant Weight in Gold', 'Gallant Game Changer', 'Gallant Talking About Love', 'Gallant Priest',
  ],

  jazz: [
    'Miles Davis So What', 'Miles Davis Freddie Freeloader', 'Miles Davis Blue in Green', 'Miles Davis All Blues', 'Miles Davis Bye Bye Blackbird',
    'John Coltrane Giant Steps', 'John Coltrane A Love Supreme', 'John Coltrane In a Sentimental Mood', 'John Coltrane My Favorite Things', 'John Coltrane Naima',
    'Charlie Parker Billie\'s Bounce', 'Charlie Parker Au Private', 'Charlie Parker Scrapple from the Apple', 'Charlie Parker Ornithology', 'Charlie Parker Barbados',
    'Billie Holiday Strange Fruit', 'Billie Holiday Lover Man', 'Billie Holiday Body and Soul', 'Billie Holiday I\'ll Be Seeing You', 'Billie Holiday All of Me',
    'Duke Ellington Take the A Train', 'Duke Ellington Mood Indigo', 'Duke Ellington Prelude to a Kiss', 'Duke Ellington Sophisticated Lady', 'Duke Ellington Caravan',
    'Ella Fitzgerald Summertime', 'Ella Fitzgerald Cheek to Cheek', 'Ella Fitzgerald Night and Day', 'Ella Fitzgerald I Got You Under My Skin', 'Ella Fitzgerald Too Darn Hot',
    'Oscar Peterson Hymn to Freedom', 'Oscar Peterson Tenderly', 'Oscar Peterson Jeepers Creepers', 'Oscar Peterson Ivy League', 'Oscar Peterson Soft Winds',
    'Art Blakey Moanin', 'Art Blakey A Night in Tunisia', 'Art Blakey The Biggest Night in My Life', 'Art Blakey Drum Thunder Suite', 'Art Blakey Rhythm',
  ],

  funk: [
    'James Brown I Feel Good', 'James Brown Papa\'s Got a Brand New Bag', 'James Brown Say It Loud I\'m Black and I\'m Proud', 'James Brown Cold Sweat', 'James Brown Try Me',
    'Earth Wind & Fire September', 'Earth Wind & Fire Fantasy', 'Earth Wind & Fire Shining Star', 'Earth Wind & Fire Boogie Wonderland', 'Earth Wind & Fire After the Love',
    'George Clinton & P-Funk One Nation Under a Groove', 'George Clinton & P-Funk Flashlight', 'George Clinton & P-Funk Mothership Connection', 'George Clinton & P-Funk Atomic Dog', 'George Clinton & P-Funk Maggot Brain',
    'Sly & The Family Stone Family Affair', 'Sly & The Family Stone If You Want Me to Stay', 'Sly & The Family Stone Everyday People', 'Sly & The Family Stone Hot Fun', 'Sly & The Family Stone Thank You',
    'Nile Rodgers & Chic Le Freak', 'Nile Rodgers & Chic I Want Your Love', 'Nile Rodgers & Chic Good Times', 'Nile Rodgers & Chic Dance Dance Dance Yowsah', 'Nile Rodgers & Chic Everybody Dance',
    'Maroon 5 Moves Like Jagger', 'Maroon 5 This Love', 'Maroon 5 Sugar', 'Maroon 5 Maps', 'Maroon 5 Animals',
  ],

  reggae: [
    'Bob Marley One Love', 'Bob Marley No Woman No Cry', 'Bob Marley Get Up Stand Up', 'Bob Marley Could You Be Loved', 'Bob Marley Buffalo Soldier',
    'Bob Marley Iron Lion Zion', 'Bob Marley Redemption Song', 'Bob Marley Three Little Birds', 'Bob Marley Stir It Up', 'Bob Marley Jamming',
    'Burning Spear Marcus Garvey', 'Burning Spear Living Africa', 'Burning Spear Slow Down', 'Burning Spear Slave Driver', 'Burning Spear Dry and Heavy',
    'Peter Tosh Legalize It', 'Peter Tosh Equal Rights', 'Peter Tosh Get Up Stand Up', 'Peter Tosh Bush Doctor', 'Peter Tosh Mama Africa',
    'Gregory Isaacs Night Nurse', 'Gregory Isaacs Rumours', 'Gregory Isaacs Love Is Overdue', 'Gregory Isaacs Private Beach Party', 'Gregory Isaacs Soon Forward',
    'Jimmy Cliff The Harder They Come', 'Jimmy Cliff Wonderful World Beautiful People', 'Jimmy Cliff Trapped', 'Jimmy Cliff Pressure Drop', 'Jimmy Cliff Vietnam',
  ]
};

module.exports = POPULAR_QUERIES;
