// @ts-nocheck

/**
 * 1000+ MÚSICAS POPULARES - Cache Warmup Database
 * Gêneros: Pop, Hip-Hop, K-Pop, Latin, Rock/Metal, Electronic
 * Pré-aqueça o cache com: npm run warmup
 */

const POPULAR_QUERIES = {
  pop: [
    'The Weeknd Blinding Lights', 'The Weeknd After Hours', 'The Weeknd Starboy',
    'Billie Eilish Bad Guy', 'Billie Eilish Therefore I Am', 'Billie Eilish Ocean Eyes',
    'Dua Lipa Levitating', 'Dua Lipa Don\'t Start Now', 'Dua Lipa Physical',
    'Ariana Grande Thank U Next', 'Ariana Grande God is a Woman', 'Ariana Grande Into You',
    'Taylor Swift Anti-Hero', 'Taylor Swift Lover', 'Taylor Swift You Belong with Me',
    'Ed Sheeran Shape of You', 'Ed Sheeran Perfect', 'Ed Sheeran Thinking Out Loud',
    'Olivia Rodrigo Drivers License', 'Olivia Rodrigo good 4 u', 'Olivia Rodrigo deja vu',
    'Miley Cyrus Flowers', 'Miley Cyrus Wrecking Ball', 'Miley Cyrus The Climb',
    'Tate McRae she\'s all i wanna be', 'Tate McRae think later', 'Tate McRae r u ok',
    'Sabrina Carpenter Nonsense', 'Sabrina Carpenter Espresso', 'Sabrina Carpenter Skin',
    'Joji Slow It Down', 'Joji Good 2 Go', 'Joji Will You',
    'Post Malone Circles', 'Post Malone Congratulations', 'Post Malone Psycho',
    'Justin Bieber Sorry', 'Justin Bieber Love Yourself', 'Justin Bieber What Do You Mean',
    'Shawn Mendes Stitches', 'Shawn Mendes Treat You Better', 'Shawn Mendes Señorita',
    'Harry Styles Watermelon Sugar', 'Harry Styles As It Was', 'Harry Styles Sign of the Times',
    'Khalid Location', 'Khalid Young Dumb & Broke', 'Khalid Lovely',
    'Sia Chandelier', 'Sia Cheap Thrills', 'Sia Elastic Heart',
    'Marshmello Alone', 'Marshmello Wolves', 'Marshmello Friends',
    'Calvin Harris Summer', 'Calvin Harris Feels', 'Calvin Harris How Deep Is Your Love',
    'Avicii Wake Me Up', 'Avicii Hey Brother', 'Avicii The Nights',
    'David Guetta Titanium', 'David Guetta Without You', 'David Guetta Memories',
    'Kygo Firestone', 'Kygo Stole the Show', 'Kygo Kids in Love',
    'Major Lazer Lean On', 'Major Lazer Dangerous', 'Major Lazer Cold Water',
    'The Chainsmokers Closer', 'The Chainsmokers Don\'t Let Me Down', 'The Chainsmokers Sick Boy',
    'Juice WRLD Lucid Dreams', 'Juice WRLD All Girls Are the Same', 'Juice WRLD Lean Wit Me',
    'Lil Nas X Old Town Road', 'Lil Nas X Montero', 'Lil Nas X INDUSTRY BABY',
    'MGMT Electric Feel', 'MGMT Kids', 'MGMT Time to Pretend',
    'Pharrell Williams Happy', 'Pharrell Williams Blurred Lines', 'Pharrell Williams Freedom',
    'HAIM The Wire', 'HAIM Right Now', 'HAIM Don\'t Save Me',
    'Bleachers Don\'t Take the Money', 'Bleachers Rollercoaster', 'Bleachers Strange Desire',
    'Tove Lo Habits', 'Tove Lo Talking Body', 'Tove Lo Chasing Hearts',
    'Saint JHN Roses', 'Saint JHN Trap', 'Saint JHN Ghetto Lenny\'s Eulogy',
    'Conan Gray Memories', 'Conan Gray Maniac', 'Conan Gray Astronomy',
  ],

  hiphop: [
    'Drake God Plan', 'Drake One Dance', 'Drake Hotline Bling', 'Drake In My Feelings',
    'Drake Headlines', 'Drake Started From The Bottom', 'Drake Work', 'Drake Passionfruit',
    'Kanye West Gold Digger', 'Kanye West Stronger', 'Kanye West All of the Lights',
    'Kanye West Heartless', 'Kanye West Black Skinhead', 'Kanye West Power',
    'Eminem Lose Yourself', 'Eminem Without Me', 'Eminem The Real Slim Shady',
    'Eminem Stan', 'Eminem Not Afraid', 'Eminem Love The Way You Lie',
    'Jay-Z Dirt Off Your Shoulder', 'Jay-Z Empire State of Mind', 'Jay-Z 99 Problems',
    'Kendrick Lamar HUMBLE', 'Kendrick Lamar DNA', 'Kendrick Lamar Swimming Pools',
    'Kendrick Lamar Sing About Me', 'Kendrick Lamar Backseat Freestyle', 'Kendrick Lamar Alright',
    'Nicki Minaj Anaconda', 'Nicki Minaj Only', 'Nicki Minaj Starship',
    'Cardi B Bodak Yellow', 'Cardi B Be Careful', 'Cardi B I Like It',
    'Cardi B WAP', 'Cardi B Kiss Me More', 'Cardi B Cardigan',
    'Travis Scott Sicko Mode', 'Travis Scott Astroworld', 'Travis Scott Goosebumps',
    'Travis Scott Antidote', 'Travis Scott Highest in the Room', 'Travis Scott Butterfly Effect',
    'Lil Baby Drip', 'Lil Baby Yes Indeed', 'Lil Baby Cash',
    'Lil Baby Southside', 'Lil Baby Out the Slums', 'Lil Baby Harder Than Ever',
    'Gunna Drip Season 3', 'Gunna Drip Too Hard', 'Gunna Ski',
    'Gunna Tycoon', 'Gunna Baby Birkin', 'Gunna Skyway',
    'Playboi Carti Magnolia', 'Playboi Carti Shoota', 'Playboi Carti Earfquake',
    'Playboi Carti @ MEH', 'Playboi Carti Sky', 'Playboi Carti Fell in Luv',
    'Tyler the Creator EARFQUAKE', 'Tyler the Creator Yonkers', 'Tyler the Creator See You Again',
    'Tyler the Creator Tamale', 'Tyler the Creator Flower Boy', 'Tyler the Creator Goblin',
    'Anderson .Paak Come Down', 'Anderson .Paak Tints', 'Anderson .Paak The Bird',
    'Anderson .Paak Bubblin', 'Anderson .Paak Ventura', 'Anderson .Paak Malibu',
    'J Cole No Role Modelz', 'J Cole Love Yourz', 'J Cole Motiv8',
    'J Cole Power Trip', 'J Cole 4 Your Eyez Only', 'J Cole Chaining Day',
    'Childish Gambino This Is America', 'Childish Gambino Redbone', 'Childish Gambino The Worst Guys',
    'Migos Bad and Boujee', 'Migos Stir Fry', 'Migos Slippery',
    'Offset Bank Account', 'Offset Clout Cobain', 'Offset Wish You Well',
    'Post Malone Congratulations', 'Post Malone Psycho', 'Post Malone Rockstar',
    'Post Malone Goodbyes', 'Post Malone White Iverson', 'Post Malone Sunroof',
    'XXXTentacion Sad', 'XXXTentacion Moonlight', 'XXXTentacion Jocelyn',
    'XXXTentacion Changes', 'XXXTentacion Look at Me', 'XXXTentacion Revenge',
    'Lil Uzi Vert XO TOUR Llif3', 'Lil Uzi Vert The Way Life Goes', 'Lil Uzi Vert Luv Scars',
    'Lil Uzi Vert Kobe', 'Lil Uzi Vert 20 Min', 'Lil Uzi Vert Diamonds',
    'Ski Mask the Slump Dog Catch Me Outside', 'Ski Mask the Slump God Babywipe',
    'Trippie Redd Moonlight', 'Trippie Redd Late Night Tripping', 'Trippie Redd Topanga',
    'Trippie Redd Love Scars', 'Trippie Redd Poles', 'Trippie Redd Snakes',
    'Don Toliver No Idea', 'Don Toliver After Party', 'Don Toliver Company',
    'NBA YoungBoy Greenlight', 'NBA YoungBoy Valuable Pain', 'NBA YoungBoy Lil Top',
  ],

  kpop: [
    'BTS Dynamite', 'BTS Butter', 'BTS Permission to Dance', 'BTS Boy With Luv',
    'BTS Spring Day', 'BTS Fake Love', 'BTS Blood Sweat & Tears', 'BTS DNA',
    'BTS Mic Drop', 'BTS Jungkook Euphoria', 'BTS Black Swan', 'BTS On',
    'BLACKPINK As If It\'s Your Last', 'BLACKPINK Kill This Love', 'BLACKPINK Ddu-Du Ddu-Du',
    'BLACKPINK Pink Venom', 'BLACKPINK Shut Down', 'BLACKPINK Whistle',
    'BLACKPINK Boombayah', 'BLACKPINK Ice Cream', 'BLACKPINK How You Like That',
    'TWICE Fancy', 'TWICE Likey', 'TWICE What Is Love', 'TWICE Feel Special',
    'TWICE Knock Knock', 'TWICE Dance the Night Away', 'TWICE Heart Shaker',
    'TWICE TT', 'TWICE Breakthrough', 'TWICE More & More', 'TWICE Set Me Free',
    'EXO Growl', 'EXO Overdose', 'EXO Call Me Baby', 'EXO Artificial Love',
    'EXO Ko Ko Bop', 'EXO Don\'t Mess Up My Tempo', 'EXO Obsession', 'EXO Monster',
    'Stray Kids God Menu', 'Stray Kids Back Door', 'Stray Kids IN生', 'Stray Kids Side Effects',
    'Stray Kids S Class', 'Stray Kids Cheese', 'Stray Kids Thunderous', 'Stray Kids Maniac',
    'Stray Kids Venom', 'Stray Kids Miroh', 'NewJeans Hype Boy', 'NewJeans Cookie',
    'NewJeans Attention Attention', 'NewJeans Super Shy', 'NewJeans ETA',
    'NewJeans OMG', 'NewJeans GET UP', 'NewJeans God God God', 'NewJeans Hurt',
    'IVE I AM', 'IVE I\'ve', 'IVE Eleven', 'IVE I AM DIVA', 'IVE Either Way',
    'IVE The Prom Queens', 'IVE Kitsch', 'IVE Supermodel', 'IVE Magnetic',
    'Seventeen God of Music', 'Seventeen God\'s Menu', 'Seventeen Clap', 'Seventeen Boom Boom',
    'Seventeen Flower', 'Seventeen Fear', 'Seventeen Super', 'Seventeen Left & Right',
    'Seventeen Very Nice', 'Seventeen Shining Diamond', 'Enhypen Blessed-Cursed',
    'Enhypen Given-Taken', 'Enhypen Drunk-Dazed', 'Enhypen Let Me Out', 'Enhypen Tamed-Dashed',
    'Enhypen Attention Attention', 'Enhypen Polaroid', 'Enhypen Not For Sale',
    'Itzy Wannabe', 'Itzy Icy', 'Itzy Dalla Dalla', 'Itzy Bet You Wanna',
    'Itzy Mafia In The Morning', 'Itzy Kill My Doubt', 'Itzy None of My Business',
    'GOT7 Just Right', 'GOT7 If You Do', 'GOT7 Fly', 'GOT7 Hard Carry',
    'Monsta X Trespass', 'Monsta X Beautiful', 'Monsta X Shoot Out', 'Monsta X Jealousy',
  ],

  latin: [
    'Bad Bunny Tití', 'Bad Bunny Dakiti', 'Bad Bunny Yonaguni', 'Bad Bunny Safaera',
    'Bad Bunny Calma', 'Bad Bunny Mia', 'Bad Bunny She Knows', 'Bad Bunny Soy Peor',
    'Bad Bunny La Jumpa', 'Bad Bunny Buscando A Bad Bunny', 'Bad Bunny Bichiyal',
    'J Balvin Mi Gente', 'J Balvin Ritmo', 'J Balvin Arcoíris', 'J Balvin Tití Me Preguntó',
    'J Balvin Amarillo', 'J Balvin Cuando Volveras', 'J Balvin Energía', 'J Balvin Negro',
    'Farruko Pepas', 'Farruko Punto G', 'Farruko Bzrp Session 53', 'Farruko Aislao',
    'Farruko Ella Baila Sola', 'Farruko Estamos Arriba', 'Farruko Krippy Kush',
    'Maluma Hawái', 'Maluma Mala Mía', 'Maluma 11 PM', 'Maluma Sobrio',
    'Maluma Felices los 4', 'Maluma Que Locura Enamorarse', 'Maluma Buscando a Bad Bunny',
    'Rauw Alejandro Provenza', 'Rauw Alejandro Beso', 'Rauw Alejandro Saoko',
    'Rauw Alejandro Información', 'Rauw Alejandro Punto G', 'Rauw Alejandro Ella Baila Sola',
    'Ozuna Tití', 'Ozuna La Jumpa', 'Ozuna Ella Y Yo', 'Ozuna Baila Baila Baila',
    'Ozuna Musica Cura', 'Ozuna Suavemente', 'Ozuna Culpa al Corazón',
    'Romeo Santos Obsesión', 'Romeo Santos Cuando Voltas', 'Romeo Santos La Llave De Mi Corazón',
    'Romeo Santos You', 'Romeo Santos Salvo Tu Amor', 'Romeo Santos Propuesta Indecente',
    'Aventura Cuando Vueltas', 'Aventura Obsesión', 'Aventura Dile Al Amor',
  ],

  rock: [
    'Killswitch Engage My Last Serenade', 'Killswitch Engage An Affliction', 'Killswitch Engage The End of Heartache',
    'Killswitch Engage Rose of Sharyn', 'Killswitch Engage This Fire Burns', 'Killswitch Engage The Way It Ends',
    'Avenged Sevenfold Bat Country', 'Avenged Sevenfold Almost Easy', 'Avenged Sevenfold Nightmare',
    'Avenged Sevenfold Unholy Confessions', 'Avenged Sevenfold A Little Piece of Heaven', 'Avenged Sevenfold Gunslinger',
    'Bullet for My Valentine Tears Dont Fall', 'Bullet for My Valentine Scream Aim Fire', 'Bullet for My Valentine Waking the Demon',
    'Bullet for My Valentine Hand of Blood', 'Bullet for My Valentine Fever', 'Bullet for My Valentine Deliver Us from Evil',
    'Dope Die MF Die', 'Dope You Spin My Head Right Round', 'Dope Fuck America', 'Dope Addiction', 'Dope Group Sex',
    'Bad Omens The Grounds', 'Bad Omens Like a Villain', 'Bad Omens Fluorescent Black', 'Bad Omens Somebody Told Me',
    'Bad Omens Exit Wounds', 'Bad Omens The Death of Love', 'Bad Omens Dethrone', 'Bad Omens Glass Houses',
    'Trivium Helix', 'Trivium What the Dead Men Say', 'Trivium Strife', 'Trivium Down from the Sky',
    'Trivium Silence the Resistance', 'Trivium Anthem We Will Stand', 'Trivium Dead and Gone', 'Trivium In Waves',
    'Parkway Drive Absolute Power', 'Parkway Drive Prey', 'Parkway Drive Horizons', 'Parkway Drive Wild Eyes',
    'Parkway Drive Idols and Empires', 'Parkway Drive The Void', 'Parkway Drive Crushed', 'Parkway Drive Leech',
    'Bring Me The Horizon Sleepwalking', 'Bring Me The Horizon throne', 'Bring Me The Horizon Can You Feel My Heart',
    'Bring Me The Horizon Shadow Moses', 'Bring Me The Horizon Doomed', 'Bring Me The Horizon Dethrone',
    'Bring Me The Horizon Crucify Me', 'Bring Me The Horizon Chelsea Smile', 'Bring Me The Horizon Blessed with a Curse',
    'Atreyu Blow', 'Atreyu My Time', 'Atreyu Becoming the Bull', 'Atreyu Roadway to Hellcome', 'Atreyu Right Side of the Bed',
    'Atreyu Demonology', 'Atreyu Shameful Metaphors', 'Atreyu Ex\'s and Oh\'s', 'Atreyu The Theft', 'Atreyu Angels Kill',
    'Escape The Fate Situations', 'Escape The Fate There Is No Shelter', 'Escape The Fate Dying is Your Latest Fashion',
    'Escape The Fate One For the Money', 'Escape The Fate This War Is Ours', 'Escape The Fate Issues',
    'Buckcherry Crazy Bitch', 'Buckcherry Lit Up', 'Buckcherry Broken Glass', 'Buckcherry Check It Out',
    'Buckcherry Everything', 'Buckcherry So Far', 'Buckcherry Bring It Back', 'Buckcherry Too Drunk to Die',
    'Breaking Benjamin So Cold', 'Breaking Benjamin Polyamorous', 'Breaking Benjamin Breath',
    'Breaking Benjamin I Will Follow You Into the Dark', 'Breaking Benjamin Fade Away', 'Breaking Benjamin Evil Angel',
    'Breaking Benjamin The Diary of Jane', 'Breaking Benjamin Light', 'Breaking Benjamin Swallow',
    'As I Lay Dying Through Struggle', 'As I Lay Dying My Own Grave', 'As I Lay Dying An Oceanic Feeling',
    'As I Lay Dying Wasted Words', 'As I Lay Dying Separation', 'As I Lay Dying The Darkest Nights',
    'Zao Stalemate', 'Zao The Funeral of God', 'Zao Tears of Separation', 'Zao Awake and Rise',
    'Zao Free Will', 'Zao Eye of the Storm', 'Zao Obsolete', 'Zao Embers and Ashes',
    'Demon Hunter Storm the Gates', 'Demon Hunter Not Ready to Die', 'Demon Hunter My Throat is an Open Grave',
    'Demon Hunter Thorns', 'Demon Hunter Dead and Gone', 'Demon Hunter One Thousand Apologies',
    'Unearth The Wrath of Unholy', 'Unearth Zombie Autopilot', 'Unearth My Will is Stronger', 'Unearth Extinction',
    'Unearth This Glorious Nightmare', 'Unearth Breathing in Faces', 'Unearth Oh What Is Left Inside',
  ]
};

module.exports = POPULAR_QUERIES;
